from django.urls import path
from app1 import views

urlpatterns = [
    path('', views.welcomeview, name="acceuille"),
    path('login/', views.login_view, name="login"),
    path('dashboard/adminn/', views.admin_dashboard, name="adminn"),
    path('dashboard/adminn/ajouter_user/', views.ajouter_nouveau_user, name="new_user"),
    path('dashboard/adminn/ajouter_user/supprimer_user/', views.supprimer_user, name="delete_user"),
    path('dashboard/adminn/lister-users/', views.lister_users, name="lister_users"),
    path('users/modifier/<int:id>/', views.modifier_user, name="modifier_user"),
    path('consulter-materielle/', views.consulter_materielle, name="consulter_materielle"),
    path('dashboard/user', views.dashboard_user, name="user_dashboard"),
    path('nouveau-mouvement/<int:id>', views.ajouter_mouvement, name="new_movement"),
    path('historique/', views.historqiue_mouvement, name="historique"),
    path('apropos/', views.a_propos_du_site, name="propos"),
    path('Signup/', views.sign_up_client, name="sign_up"),
    path('client/consulter-materielle/', views.consulter_materiel, name="consutler_materiel-client"),
    path('client/commander-client/<int:id>', views.commander, name="commander-client"),
    path('dashboard/comerciale', views.comercial_dashboard, name="comercial-dashboard"),
    path('dashboard/commerciale/notifications', views.notification_comerciale, name="notifications_comerciale"),
    path('dashboard/commerciale/liste-commandes', views.liste_commande_assinger, name="liste_commande_assinger"),
    path('dashboard/commerciale/historique', views.historique_commande_passe, name="historique_commande_passe"),
    path('dashboard/client/', views.dashboard_client, name="dashboard_client"),
    path('dashboard/client/notifications', views.consulter_notification_client, name="notifications_client"),
    path('dashboard/client/historique', views.historique_commande_passer_client,
         name="historique_commande_passer_client"),
    path('panier/', views.afficher_panier, name='afficher_panier'),
    path('ajouter-au-panier/<int:id>/', views.ajouter_au_panier, name='ajouter_au_panier'),
    path('panier/supprimer/<int:id>/', views.supprimer_du_panier, name='supprimer_du_panier'),
    path('panier/passer_commande/', views.passer_commande, name='passer_commande'),
    path('dashboard/client/telecharger-recue/<int:id>', views.telecharger_recue, name='generer_pdf'),
    path('dashboard/admin/ajouter-materiel/', views.ajouter_materiel, name='ajouter_mat'),
    path('dashboard/admin/lister-materiel/', views.lister_materiel, name='lister_mat'),
    path('dashboard/admin/modifier-materiel/<int:id>', views.modifier_materiel, name='modifier_mat'),
    path('dashboard/admin/supprimer-materiel/', views.supprimer_materiel, name='supprimer_mat'),
    path('deconnexion/', views.log_out, name='logout'),
    path('dashboard/admin/notifcations', views.notification_admin, name='notification_admin'),
    path('dashboard/technicien/notifcations', views.notifications_technicien, name='notifications_technicien'),
    path('dashboard/technicien/', views.technicien_dashboard, name='technicien_dashboard'),
    path('dashboard/technicien/installation', views.technicien_commande_concerner,
         name='technicien_commande_concerner'),
    path('dashboard/technicien/historique', views.historique_commande_concerner_technicien,
         name='historique_installations'),
    path('dashboard/technicien/historique-mouvements', views.technicien_hstoriqeu_mouvements,
         name='historique_mouvements'),
    path('dashboard/admin/risque-de-rupture', views.liste_des_produits_depasser_seuil_min, name='alerte'),
    path('dashboard/admin/commande_a_traiter', views.liste_commande_a_traiter, name='a_traiter'),
    path('dashboard/admin/historique_approuver', views.historique_commande_finaliser,
         name='historique_commande_approuver'),
    path('dashboard/client/chercher', views.searched, name='chercher'),
    path('dashboard/admin/alerte_stocke', views.produit_en_rupture_de_stocke, name='rupture_de_stocke'),
    path('dashboard/technicien/preparer', views.preparer_commande_technicien, name='commande_preparer'),
    path('dashboard/coursier/', views.dashbaord_coursier, name='coursier_dashboard'),
    path('dashboard/coursier/commandes_assigner', views.liste_commande_assinger_coursier, name='commande_coursier'),
    path('dashboard/commerciale/commandes-afinisaliser', views.liste_commandes_finsaliser_commerciale,
         name='commande_finsaliser'),
    path('dashboard/technicien/commandes-installer', views.commande_a_installer_technicien, name='commande_installer'),
    path('dashboard/client/recue-commande/<int:id>', views.telecharger_recue2, name='recue_commande'),
    path('dashboard/commerciale/avis', views.avis_client_sur_commande, name='avis_client'),

    # URLs pour la négociation de devis
    path('dashboard/commerciale/demandes-devis/', views.liste_demandes_devis, name='demandes_devis'),
    path('dashboard/commerciale/negocier-devis/<int:id>/', views.negocier_devis, name='negocier_devis'),
    path('dashboard/commerciale/envoyer-devis/<int:id>/', views.envoyer_devis, name='envoyer_devis'),
    path('dashboard/client/devis-recus/', views.devis_client, name='devis_client'),
    path('dashboard/client/repondre-devis/<int:id>/', views.repondre_devis, name='repondre_devis'),

    # URLs pour les interventions
    path('dashboard/technicien/fiche-intervention/', views.fichier_intervention, name='fiche_intervention'),
    path('dashboard/technicien/upload-intervention/', views.uploader_fiche_intervention, name='upload_intervention'),
    path('dashboard/admin/historique-interventions/', views.historique_intervention, name='historique_intervention'),
    path('dashboard/admin/nombre-interventions/', views.nombre_intervention_par_user, name='nombre_interventions'),

    # URLs pour les temps écoulés
    path('dashboard/coursier/temps-ecoule/', views.temps_ecoule_avant_date_limiter, name='temps_ecoule_coursier'),
    path('dashboard/commerciale/temps-ecoule/', views.temps_ecoule_avant_date_limiter_commercial,
         name='temps_ecoule_commercial'),
    path('dashboard/technicien/temps-ecoule/', views.temps_ecoule_avant_date_limiter_technicien,
         name='temps_ecoule_technicien'),

    # URLs pour les imports (fonctions existantes)
    path('dashboard/admin/import-users/', views.import_users, name='import_users'),
    path('dashboard/admin/import-clients/', views.import_clients, name='import_clients'),
    path('dashboard/admin/import-commandes/', views.import_commandes, name='import_commandes'),
    path('dashboard/admin/import-coursier-commandes/', views.import_couriser_commandes,
         name='import_coursier_commandes'),
    path('dashboard/admin/import-installations/', views.import_installations_techncien, name='import_installations'),
    path('dashboard/admin/import-preparations/', views.import_preparer_technicien, name='import_preparations'),
    path('dashboard/admin/import-mouvements/', views.import_mouvements, name='import_mouvements'),
]