# Generated by Django 4.2 on 2025-07-24 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_limite',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='penalite',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
