# Generated by Django 4.2 on 2025-07-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_commande_date_limite_commande_penalite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinterventino',
            old_name='date_commande',
            new_name='date_ajout',
        ),
    ]
