# Generated by Django 4.2 on 2025-08-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_produit_lignecommande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_limite',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='penalite',
        ),
    ]
