# Generated by Django 4.2 on 2025-07-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_date_commande_userinterventino_date_ajout'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichier_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
